server:
    port: 8090



spring:
    jackson:
        serialization:
            indent-output: true

    datasource:
        initialization-mode: always
#        data: classpath:data.sql
        url: jdbc:postgresql://localhost:5432/twf
        username: postgres
        password: twf

    jpa:
        generate-ddl: false
        hibernate:
            ddl-auto: create

        show-sql: true
